version: '3'

services:
  tesloNest:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: teslo-nest
    container_name: tesloNest
    restart: always 
    ports:
      - "${PORT}:${PORT}"
    environment:
      STAGE: ${STAGE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: postgres:14.3
    container_name: teslodb
    restart: always
    ports:
      - ${DB_PORT}:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - ./postgres:/var/lib/postgresql/data
